# Generated by Django 3.1.6 on 2021-05-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_details',
            name='email',
        ),
    ]
