# Generated by Django 3.1.6 on 2021-06-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210521_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_to',
            field=models.DateField(null=True),
        ),
    ]
