# Generated by Django 3.1.6 on 2021-06-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210607_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_to',
            field=models.DateField(null=True),
        ),
    ]
