# Generated by Django 3.1.6 on 2021-06-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20210607_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='expired_date',
            field=models.TextField(default='Enter Expired Date'),
        ),
    ]
