# Generated by Django 3.1.6 on 2021-06-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20210608_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='expired_date',
            field=models.TextField(blank=None, default='Enter Expired Date'),
        ),
    ]
