# Generated by Django 3.1.6 on 2021-06-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20210611_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_link',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
