# Generated by Django 3.1.6 on 2021-06-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_to',
            field=models.DateField(null=True),
        ),
    ]
