# Generated by Django 3.1.6 on 2021-05-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=20, unique=True, verbose_name='user_email'),
        ),
    ]
